import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { ArrowRight, Loader2, Mail, Phone, RefreshCw } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { AuthError, AuthLayout, AuthSuccess, BackToSignIn, GoogleAuthButton, OtpInput, PasswordField, PasswordRequirements } from "@/components/auth-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const Field = ({ label, value, onChange, type = "text", placeholder, autoComplete, error }: { label: string; value: string; onChange: (v: string) => void; type?: string; placeholder?: string; autoComplete?: string; error?: string }) => <label className="grid gap-2 text-sm font-semibold text-ink"><span>{label}</span><Input value={value} onChange={e => onChange(e.target.value)} type={type} placeholder={placeholder} autoComplete={autoComplete} aria-invalid={Boolean(error)} className="h-12 rounded-xl border-ink/15" />{error && <span className="text-xs font-medium text-red-700" role="alert">{error}</span>}</label>;
const Busy = () => <Loader2 className="mr-2 size-4 animate-spin" />;

export function Login() {
  const [, navigate] = useLocation(); const { login, googleLogin } = useAuth(); const [identifier, setIdentifier] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [googleLoading, setGoogleLoading] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(""); if (!identifier || !password) { setError("Enter your email or phone number and password."); return; } setLoading(true); const result = await login(identifier, password); setLoading(false); if (!result.ok) { setError(result.reason === "disabled" ? "This account is currently suspended. Please contact support." : result.reason === "unverified" ? "This account is not verified yet. Verify your account to continue." : result.reason === "service" ? "We couldn't sign you in right now. Please try again." : "That email/phone number and password combination isn't correct."); return; } navigate("/"); }
  async function google() { setGoogleLoading(true); const result = await googleLogin(); setGoogleLoading(false); if (result.ok) navigate("/"); else setError("Google sign-in was not completed. You can try again or use your password."); }
  return <AuthLayout title="Welcome back"><form onSubmit={submit} className="grid gap-4"><p className="-mt-3 text-sm text-ink/55">Sign in to manage your shipments.</p>{error && <AuthError>{error}{error.includes("verified") && <Link href="/verify" className="ml-1 font-bold underline">Verify account</Link>}</AuthError>}<Field label="Email or phone" value={identifier} onChange={setIdentifier} autoComplete="email" placeholder="you@example.com" /><PasswordField label="Password" value={password} onChange={setPassword} /><div className="flex items-center justify-end"><Link href="/forgot-password" className="text-sm font-semibold text-ink underline underline-offset-2">Forgot password?</Link></div><Button className="h-12 rounded-xl bg-cargo-yellow font-bold text-ink hover:bg-cargo-yellow/90" disabled={loading}>{loading && <Busy />}Sign in</Button><div className="flex items-center gap-3 text-xs text-ink/35"><span className="h-px flex-1 bg-ink/10" />or<span className="h-px flex-1 bg-ink/10" /></div><GoogleAuthButton onClick={google} loading={googleLoading} /><p className="text-center text-sm text-ink/55">Don't have an account? <Link href="/register" className="font-bold text-ink underline underline-offset-2">Create account</Link></p></form></AuthLayout>;
}

export function Register() {
  const [, navigate] = useLocation(); const { register, googleLogin } = useAuth(); const [form, setForm] = useState({ firstName: "", lastName: "", email: "", phone: "", password: "", confirm: "" }); const [accepted, setAccepted] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const set = (key: keyof typeof form) => (value: string) => setForm(prev => ({ ...prev, [key]: value }));
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(""); if (Object.values(form).some(v => !v)) { setError("Complete all required fields to create your account."); return; } if (!/^[^@]+@[^@]+\.[^@]+$/.test(form.email)) { setError("Enter a valid email address."); return; } if (form.password.length < 8 || !/[A-Z]/.test(form.password) || !/\d/.test(form.password)) { setError("Choose a password that meets the requirements below."); return; } if (form.password !== form.confirm) { setError("Your passwords do not match."); return; } if (!accepted) { setError("Please accept the Terms and Privacy Policy to continue."); return; } setLoading(true); const result = await register({ ...form, password: form.password }); setLoading(false); if (!result.ok) { setError(result.reason === "existing" ? "An account already exists with those details. Try signing in instead." : "We couldn't create your account right now. Please try again."); return; } navigate("/verify"); }
  return <AuthLayout title="Create your account"><form onSubmit={submit} className="grid gap-3"><p className="-mt-3 mb-2 text-sm text-ink/55">Keep every shipment within reach.</p>{error && <AuthError>{error}</AuthError>}<div className="grid gap-3 sm:grid-cols-2"><Field label="First name" value={form.firstName} onChange={set("firstName")} autoComplete="given-name" /><Field label="Last name" value={form.lastName} onChange={set("lastName")} autoComplete="family-name" /></div><Field label="Email address" value={form.email} onChange={set("email")} autoComplete="email" /><Field label="Phone number" value={form.phone} onChange={set("phone")} autoComplete="tel" /><PasswordField label="Password" value={form.password} onChange={set("password")} autoComplete="new-password" /><PasswordRequirements password={form.password} /><PasswordField label="Confirm password" value={form.confirm} onChange={set("confirm")} autoComplete="new-password" /><label className="flex items-start gap-2 py-1 text-xs leading-5 text-ink/60"><input type="checkbox" checked={accepted} onChange={e => setAccepted(e.target.checked)} className="mt-1 accent-[#FFC83D]" />I agree to the <Link href="/settings/legal/terms" className="font-semibold text-ink underline">Terms</Link> and <Link href="/settings/legal/privacy" className="font-semibold text-ink underline">Privacy Policy</Link>.</label><Button className="h-12 rounded-xl bg-cargo-yellow font-bold text-ink hover:bg-cargo-yellow/90" disabled={loading}>{loading && <Busy />}Create account</Button><GoogleAuthButton onClick={() => { googleLogin().then(() => navigate("/auth/complete-profile")); }} /><p className="text-center text-sm text-ink/55">Already have an account? <Link href="/login" className="font-bold text-ink underline">Sign in</Link></p></form></AuthLayout>;
}

export function Verify() {
  const [, navigate] = useLocation(); const { verify, resendVerification } = useAuth(); const [code, setCode] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState(false); const [loading, setLoading] = useState(false); const [resending, setResending] = useState(false); const [resent, setResent] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(""); setLoading(true); const result = await verify(code); setLoading(false); if (!result.ok) { setError(result.reason === "incomplete" ? "Enter all six digits." : result.reason === "expired" ? "That code has expired. Request a new code." : result.reason === "attempts" ? "Too many attempts. Request a fresh code to continue." : "That code is not correct. Try again."); return; } setSuccess(true); setTimeout(() => navigate("/"), 700); }
  async function resend() { setResending(true); const result = await resendVerification(); setResending(false); if (result.ok) { setCode(""); setError(""); setResent(true); } }
  return <AuthLayout title="Verify your account"><form onSubmit={submit} className="grid gap-5"><p className="-mt-3 text-sm leading-6 text-ink/55">We've sent a 6-digit code to your phone or email. For this demo, use <strong className="text-ink">123456</strong>.</p>{success ? <AuthSuccess title="Account verified">You’re ready to continue.</AuthSuccess> : <>{error && <AuthError>{error}</AuthError>}<div className="grid justify-items-center gap-3"><OtpInput value={code} onChange={setCode} /><button type="button" onClick={resend} disabled={resending} className="inline-flex items-center gap-2 text-sm font-semibold text-ink disabled:opacity-60"><RefreshCw className={`size-4 ${resending ? "animate-spin" : ""}`} />{resending ? "Sending code" : resent ? "Code resent" : "Resend code"}</button></div><Button className="h-12 rounded-xl bg-cargo-yellow font-bold text-ink" disabled={loading}>{loading && <Busy />}Verify</Button><Link href="/login" className="text-center text-sm font-semibold text-ink/55">Change email or phone</Link></>}</form></AuthLayout>;
}

export function ForgotPassword() {
  const [identifier, setIdentifier] = useState(""); const [sent, setSent] = useState(false); const [error, setError] = useState("");
  return <AuthLayout title="Reset your password">{sent ? <div className="grid gap-5"><AuthSuccess title="Check your messages">If an account exists for those details, we've sent instructions for resetting your password.</AuthSuccess><div className="flex justify-between"><button onClick={() => setSent(false)} className="text-sm font-semibold text-ink">Use another email/phone</button><Link href="/reset-password" className="text-sm font-semibold text-ink underline">Open reset page</Link></div><BackToSignIn /></div> : <form onSubmit={e => { e.preventDefault(); if (!identifier) setError("Enter an email address or phone number."); else { setError(""); setSent(true); } }} className="grid gap-5"><p className="-mt-3 text-sm leading-6 text-ink/55">Enter the email or phone number linked to your account.</p>{error && <AuthError>{error}</AuthError>}<Field label="Email or phone" value={identifier} onChange={setIdentifier} autoComplete="email" placeholder="you@example.com" /><Button className="h-12 rounded-xl bg-cargo-yellow font-bold text-ink">Send reset instructions</Button><BackToSignIn /></form>}</AuthLayout>;
}

export function ResetPassword() {
  const [, navigate] = useLocation(); const { resetPassword } = useAuth(); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState(false); const [loading, setLoading] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(""); if (password !== confirm) { setError("Your passwords do not match."); return; } if (password.length < 8 || !/[A-Z]/.test(password) || !/\d/.test(password)) { setError("Choose a password that meets the requirements below."); return; } setLoading(true); await resetPassword(password); setLoading(false); setSuccess(true); }
  return <AuthLayout title="Create a new password">{success ? <div className="grid gap-5"><AuthSuccess title="Password updated">Your password has been updated successfully.</AuthSuccess><Button onClick={() => navigate("/login")} className="h-12 rounded-xl bg-cargo-yellow font-bold text-ink">Continue to sign in</Button></div> : <form onSubmit={submit} className="grid gap-4">{error && <AuthError>{error}</AuthError>}<PasswordField label="New password" value={password} onChange={setPassword} autoComplete="new-password" /><PasswordRequirements password={password} /><PasswordField label="Confirm new password" value={confirm} onChange={setConfirm} autoComplete="new-password" /><Button className="h-12 rounded-xl bg-cargo-yellow font-bold text-ink" disabled={loading}>{loading && <Busy />}Reset password</Button></form>}</AuthLayout>;
}

export function CompleteProfile() {
  const [, navigate] = useLocation(); const { user, updateUser } = useAuth(); const [phone, setPhone] = useState(user?.phone || ""); const [country, setCountry] = useState("Zambia"); const [error, setError] = useState("");
  return <AuthLayout title="Complete your profile"><form onSubmit={e => { e.preventDefault(); if (!phone) { setError("Add a phone number so we can keep you updated."); return; } updateUser({ phone }); navigate("/"); }} className="grid gap-4"><p className="-mt-3 text-sm leading-6 text-ink/55">A few details help New World Cargo keep your delivery updates accurate.</p>{error && <AuthError>{error}</AuthError>}<Field label="Phone number" value={phone} onChange={setPhone} autoComplete="tel" /><Field label="Country" value={country} onChange={setCountry} /><Button className="h-12 rounded-xl bg-cargo-yellow font-bold text-ink">Continue</Button></form></AuthLayout>;
}

export function SessionExpired() { const [, navigate] = useLocation(); return <AuthLayout title="Your session has expired"><div className="grid gap-5"><p className="text-sm leading-6 text-ink/60">For your security, please sign in again. We’ll take you back to your customer workspace.</p><Button onClick={() => navigate("/login?returnTo=/")} className="h-12 rounded-xl bg-cargo-yellow font-bold text-ink">Sign in again <ArrowRight className="ml-2 size-4" /></Button></div></AuthLayout>; }
