// New World Cargo style reminder: Poppins, dark command-center canvas, Cargo Yellow action color, lavender route accents, mobile-first.

import { Bell, CheckCircle2, Clock3, MapPin, PackageCheck, WalletCards } from "lucide-react";
import { useLocation } from "wouter";
import { shipments } from "@/lib/mock-data";
import { CargoRail } from "@/components/shipment-ui";

const notifications = [
  { id: 1, type: "progress", title: "Your package is in transit", body: "NWC48291ZM is moving through our delivery network.", time: "12 min ago", icon: PackageCheck, color: "text-route-lavender", bg: "bg-route-lavender/15", shipment: "shipment-48291", unread: true },
  { id: 2, type: "arrival", title: "Courier is nearby", body: "NWC19034ZM is arriving today in Ndola.", time: "1 hr ago", icon: MapPin, color: "text-mint", bg: "bg-mint/15", shipment: "shipment-19034", unread: true },
  { id: 3, type: "exception", title: "Delivery needs your attention", body: "We couldn't reach the recipient for NWC77120ZM.", time: "Yesterday", icon: Clock3, color: "text-coral", bg: "bg-coral/15", shipment: "shipment-77120", unread: false },
  { id: 4, type: "payment", title: "Payment confirmed", body: "Your receipt for NWC48291ZM is ready to view.", time: "12 Aug", icon: WalletCards, color: "text-cargo-yellow", bg: "bg-cargo-yellow/15", shipment: "shipment-48291", unread: false },
];

export default function Notifications() { const [, navigate] = useLocation(); return <div className="mx-auto max-w-3xl"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-cargo-yellow">Stay in the loop</p><h1 className="mt-2 font-heading text-3xl font-extrabold tracking-tight sm:text-4xl">Notifications</h1><p className="mt-2 text-sm text-white/45">The next useful thing, right when you need it.</p></div><button className="hidden text-xs font-bold text-white/40 hover:text-white sm:block">Mark all read</button></div><div className="mt-6"><CargoRail label="Shipment signals" items={["Created", "Moving", "Arriving", "Delivered"]} active={1} /></div><div className="mt-8 space-y-3">{notifications.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => navigate(`/shipments/${item.shipment}`)} className={`flex w-full gap-4 rounded-[24px] border p-4 text-left transition hover:border-white/20 sm:p-5 ${item.unread ? "border-white/12 bg-white/[0.045]" : "border-white/7 bg-white/[0.02]"}`}><div className={`grid size-11 shrink-0 place-items-center rounded-2xl ${item.bg} ${item.color}`}><Icon className="size-5" /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="text-sm font-bold">{item.title}</p>{item.unread && <span className="mt-1 size-2 shrink-0 rounded-full bg-coral" />}</div><p className="mt-1 text-sm leading-5 text-white/45">{item.body}</p><p className="mt-3 text-[11px] text-white/25">{item.time}</p></div></button>; })}</div><div className="mt-8 flex items-center gap-3 rounded-2xl border border-mint/15 bg-mint/6 p-4 text-xs text-white/45"><CheckCircle2 className="size-4 text-mint" />You’re all caught up for now. We’ll notify you when something changes.</div></div>; }
