// New World Cargo style reminder: one customer task per page, clear back route, soft white surfaces, and Cargo Yellow only for primary action.

import { ArrowLeft, Bell, Check, ChevronRight, CircleUserRound, CreditCard, FileText, LockKeyhole, MapPin, Pencil, Plus, ReceiptText, ShieldCheck, Smartphone, UsersRound, WalletCards } from "lucide-react";
import { useState } from "react";
import { useLocation, useRoute } from "wouter";
import { toast } from "sonner";
import { addresses, recipients } from "@/lib/mock-data";

type SettingSection = "account" | "addresses" | "recipients" | "notifications" | "payment-methods" | "security" | "billing";
type SectionMeta = { title: string; subtitle: string; icon: typeof CircleUserRound; accent: string };

const meta: Record<SettingSection, SectionMeta> = {
  account: { title: "Account details", subtitle: "Keep your contact details ready for every cargo update.", icon: CircleUserRound, accent: "bg-route-lavender/15 text-route-lavender" },
  addresses: { title: "Saved addresses", subtitle: "Use a familiar pickup or delivery point in fewer taps.", icon: MapPin, accent: "bg-cargo-yellow/18 text-ink" },
  recipients: { title: "Saved recipients", subtitle: "Your regular delivery contacts, ready for the next shipment.", icon: UsersRound, accent: "bg-mint/30 text-emerald-800" },
  notifications: { title: "Notifications", subtitle: "Choose which cargo updates reach you.", icon: Bell, accent: "bg-route-lavender/15 text-route-lavender" },
  "payment-methods": { title: "Payment methods", subtitle: "Mobile money, cards, and payment preferences.", icon: CreditCard, accent: "bg-cargo-yellow/18 text-ink" },
  security: { title: "Security", subtitle: "Protect your account and keep your contact verified.", icon: ShieldCheck, accent: "bg-mint/30 text-emerald-800" },
  billing: { title: "Receipts & billing", subtitle: "Review invoices, payment records, and receipts.", icon: WalletCards, accent: "bg-route-lavender/15 text-route-lavender" },
};

function Panel({ children }: { children: React.ReactNode }) { return <section className="overflow-hidden rounded-[26px] border border-ink/10 bg-white">{children}</section>; }
function Row({ children, onClick }: { children: React.ReactNode; onClick?: () => void }) { return <button onClick={onClick} className="flex w-full items-center gap-3.5 px-4 py-4 text-left transition hover:bg-ink/[0.025] sm:px-5">{children}</button>; }
function Toggle({ enabled, onChange }: { enabled: boolean; onChange: (value: boolean) => void }) { return <button onClick={() => onChange(!enabled)} className={`relative h-7 w-12 shrink-0 rounded-full transition ${enabled ? "bg-cargo-yellow" : "bg-ink/15"}`} aria-pressed={enabled}><span className={`absolute top-1 size-5 rounded-full bg-white shadow-sm transition ${enabled ? "left-6" : "left-1"}`} /></button>; }

export default function SettingsDetail() {
  const [, params] = useRoute("/settings/:section");
  const [, navigate] = useLocation();
  const requestedSection = params?.section;
  const section = (requestedSection && requestedSection in meta ? requestedSection : "account") as SettingSection;
  const current = meta[section];
  const Icon = current.icon;
  const [alerts, setAlerts] = useState({ movement: true, delivery: true, billing: true, news: false });

  const content = () => {
    if (section === "account") return <div className="space-y-4"><Panel><div className="flex items-center gap-4 p-5"><span className="grid size-14 place-items-center rounded-3xl bg-route-lavender text-lg font-extrabold text-white">AM</span><div className="min-w-0 flex-1"><p className="font-heading text-lg font-extrabold">Amina Mwansa</p><p className="mt-1 text-xs text-ink/50">Personal account · Lusaka, Zambia</p></div><button onClick={() => toast("Profile editing is ready for your details.")} className="grid size-10 place-items-center rounded-full border border-ink/10 text-ink/55 hover:bg-ink/5" aria-label="Edit profile"><Pencil className="size-4" /></button></div><div className="border-t border-ink/8"><Row onClick={() => toast("Email verification settings opened.")}><span className="grid size-9 place-items-center rounded-xl bg-mint/30 text-emerald-800"><Check className="size-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">amina.banda@example.com</span><span className="mt-1 block text-xs text-ink/50">Verified email</span></span><ChevronRight className="size-4 text-ink/35" /></Row><Row onClick={() => toast("Phone number editing is ready.")}><span className="grid size-9 place-items-center rounded-xl bg-cargo-yellow/18 text-ink"><Smartphone className="size-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">+260 977 123 456</span><span className="mt-1 block text-xs text-ink/50">Verified mobile number</span></span><ChevronRight className="size-4 text-ink/35" /></Row></div></Panel></div>;
    if (section === "addresses") return <div className="space-y-4"><button onClick={() => toast("Add address form opened.")} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-cargo-yellow px-4 py-3.5 text-sm font-bold text-ink"><Plus className="size-4" /> Add an address</button><Panel>{addresses.map((address, index) => <Row key={address.id} onClick={() => toast(`${address.label} is ready to edit.`)}><span className="grid size-10 place-items-center rounded-2xl bg-cargo-yellow/18 text-ink"><MapPin className="size-4" /></span><span className={`min-w-0 flex-1 ${index ? "border-t-0" : ""}`}><span className="flex items-center gap-2"><span className="text-sm font-bold">{address.label}</span>{address.default && <span className="rounded-full bg-mint/30 px-2 py-0.5 text-[9px] font-bold text-emerald-800">Default</span>}</span><span className="mt-1 block text-xs text-ink/50">{address.line}</span></span><ChevronRight className="size-4 text-ink/35" /></Row>)}</Panel></div>;
    if (section === "recipients") return <div className="space-y-4"><button onClick={() => toast("Add recipient form opened.")} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-cargo-yellow px-4 py-3.5 text-sm font-bold text-ink"><Plus className="size-4" /> Add a recipient</button><Panel>{recipients.map((recipient) => <Row key={recipient.id} onClick={() => navigate("/send")}><span className="grid size-10 place-items-center rounded-full bg-route-lavender/15 text-xs font-bold text-route-lavender">{recipient.initials}</span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">{recipient.name}</span><span className="mt-1 block text-xs text-ink/50">{recipient.location} · {recipient.phone}</span></span><ChevronRight className="size-4 text-ink/35" /></Row>)}</Panel></div>;
    if (section === "notifications") return <Panel>{([{ key: "movement", title: "Shipment movement", detail: "Pickup, departure, and route updates" }, { key: "delivery", title: "Delivery updates", detail: "Arrival, handover, and proof of delivery" }, { key: "billing", title: "Billing reminders", detail: "Invoices due and payment confirmations" }, { key: "news", title: "Helpful updates", detail: "Service news and shipping guidance" }] as const).map((item, index) => <div key={item.key} className={`flex items-center gap-4 px-4 py-4 sm:px-5 ${index ? "border-t border-ink/8" : ""}`}><span className="min-w-0 flex-1"><span className="block text-sm font-bold">{item.title}</span><span className="mt-1 block text-xs text-ink/50">{item.detail}</span></span><Toggle enabled={alerts[item.key]} onChange={(value) => setAlerts((previous) => ({ ...previous, [item.key]: value }))} /></div>)}</Panel>;
    if (section === "payment-methods") return <div className="space-y-4"><Panel><Row onClick={() => toast("Mobile money is your preferred payment method.")}><span className="grid size-10 place-items-center rounded-2xl bg-cargo-yellow/18 text-ink"><Smartphone className="size-4" /></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className="text-sm font-bold">Mobile money</span><span className="rounded-full bg-mint/30 px-2 py-0.5 text-[9px] font-bold text-emerald-800">Preferred</span></span><span className="mt-1 block text-xs text-ink/50">Airtel Money · +260 977 123 456</span></span><ChevronRight className="size-4 text-ink/35" /></Row><Row onClick={() => toast("You can add an ATM or debit card during your next payment.")}><span className="grid size-10 place-items-center rounded-2xl bg-route-lavender/15 text-route-lavender"><CreditCard className="size-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">ATM / debit card</span><span className="mt-1 block text-xs text-ink/50">Add a card securely when you pay</span></span><ChevronRight className="size-4 text-ink/35" /></Row></Panel><div className="rounded-2xl border border-ink/10 bg-[#f7f8fb] p-4 text-xs leading-5 text-ink/55">When you pay an invoice or booking deposit, the payment screen remembers your last successful method.</div></div>;
    if (section === "security") return <Panel><Row onClick={() => toast("Password update form opened.")}><span className="grid size-10 place-items-center rounded-2xl bg-route-lavender/15 text-route-lavender"><LockKeyhole className="size-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">Password</span><span className="mt-1 block text-xs text-ink/50">Last changed 3 months ago</span></span><ChevronRight className="size-4 text-ink/35" /></Row><Row onClick={() => toast("Verified contact settings opened.")}><span className="grid size-10 place-items-center rounded-2xl bg-mint/30 text-emerald-800"><Check className="size-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">Verified contact details</span><span className="mt-1 block text-xs text-ink/50">Email and mobile number confirmed</span></span><ChevronRight className="size-4 text-ink/35" /></Row><Row onClick={() => toast("Sign-in activity is ready to review.")}><span className="grid size-10 place-items-center rounded-2xl bg-cargo-yellow/18 text-ink"><ShieldCheck className="size-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">Sign-in activity</span><span className="mt-1 block text-xs text-ink/50">Review the devices using your account</span></span><ChevronRight className="size-4 text-ink/35" /></Row></Panel>;
    return <div className="space-y-4"><div className="relative overflow-hidden rounded-[26px] border border-ink/10 bg-[#f7f8fb] p-5"><div className="absolute -bottom-6 right-7 size-16 rounded-2xl border-[10px] border-route-lavender/20" /><div className="relative flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-ink/45">Billing snapshot</p><p className="mt-2 font-heading text-3xl font-extrabold">K 1,280 due</p><p className="mt-2 text-xs leading-5 text-ink/55">One invoice is waiting for payment. Paid invoices include a downloadable receipt.</p></div><span className="grid size-10 place-items-center rounded-2xl bg-cargo-yellow text-ink"><ReceiptText className="size-5" /></span></div></div><button onClick={() => navigate("/invoices")} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-cargo-yellow px-4 py-3.5 text-sm font-bold text-ink">Open invoices & receipts <ChevronRight className="size-4" /></button><Panel><Row onClick={() => navigate("/invoices")}><span className="grid size-10 place-items-center rounded-2xl bg-route-lavender/15 text-route-lavender"><FileText className="size-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">Home goods</span><span className="mt-1 block text-xs text-ink/50">NWC-INV-0812 · Unpaid · K 1,280</span></span><ChevronRight className="size-4 text-ink/35" /></Row></Panel></div>;
  };

  return <div className="mx-auto max-w-3xl text-ink"><button onClick={() => navigate("/settings")} className="flex items-center gap-2 text-sm font-bold text-ink/55 transition hover:text-ink"><ArrowLeft className="size-4" /> Back to settings</button><div className="mt-7 flex items-start gap-4"><span className={`grid size-12 place-items-center rounded-2xl ${current.accent}`}><Icon className="size-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-cargo-yellow">Settings</p><h1 className="mt-1 font-heading text-3xl font-extrabold tracking-tight">{current.title}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-ink/55">{current.subtitle}</p></div></div><div className="relative mt-6 overflow-hidden rounded-2xl border border-ink/10 bg-[#f7f8fb] px-4 py-3"><div className="absolute -bottom-6 right-6 size-14 rounded-2xl border-[9px] border-route-lavender/20" /><div className="relative flex items-center gap-3"><span className="size-2 rounded-full bg-mint" /><span className="h-px min-w-7 flex-1 bg-mint" /><span className="size-3 rounded-full border-2 border-route-lavender bg-white shadow-[0_0_0_4px_rgba(129,120,255,0.14)]" /><span className="h-px min-w-7 flex-1 border-t border-dashed border-ink/20" /><span className="size-2 rounded-full bg-ink/25" /><span className="ml-1 whitespace-nowrap text-[10px] font-extrabold uppercase tracking-[0.15em] text-route-lavender">Customer control</span></div></div><div className="mt-6">{content()}</div></div>;
}
