import { ArrowLeft, Check, Laptop, LogOut, MapPin, ShieldCheck, Smartphone } from "lucide-react";
import { useLocation } from "wouter";
import { useCustomerSessionActivity, useSessionActivityMutations } from "@/api/hooks";
import { ErrorState, LoadingState } from "@/components/async-state";
import { Button } from "@/components/ui/button";

export default function SignInActivity() {
  const [, navigate] = useLocation();
  const sessionsQuery = useCustomerSessionActivity();
  const sessionMutations = useSessionActivityMutations();
  if (sessionsQuery.isLoading) return <LoadingState label="Loading sign-in activity…" />;
  if (sessionsQuery.isError) return <ErrorState title="We could not load sign-in activity" detail="Please try again." action={{ label: "Try again", onClick: () => sessionsQuery.refetch() }} />;
  const sessions = sessionsQuery.data ?? [];
  const current = sessions.find((session) => session.current);
  return <div className="mx-auto max-w-3xl text-ink">
    <button type="button" onClick={() => navigate("/settings/security")} className="flex items-center gap-2 text-sm font-bold text-ink/55 transition hover:text-ink"><ArrowLeft className="size-4" /> Back to security</button>
    <div className="mt-7 flex items-start gap-4"><span className="grid size-12 place-items-center rounded-2xl bg-cargo-yellow/18 text-ink"><ShieldCheck className="size-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-cargo-yellow">Security</p><h1 className="mt-1 font-heading text-3xl font-extrabold tracking-tight">Sign-in activity</h1><p className="mt-2 max-w-xl text-sm leading-6 text-ink/55">Review where your account is signed in and remove sessions you do not recognize.</p></div></div>
    <div className="relative mt-6 overflow-hidden rounded-2xl border border-ink/10 bg-[#f7f8fb] px-4 py-3"><div className="relative flex items-center gap-3"><span className="size-2 rounded-full bg-cargo-yellow" /><span className="h-px min-w-7 flex-1 bg-cargo-yellow" /><span className="size-3 rounded-full border-2 border-cargo-yellow bg-white shadow-[0_0_0_4px_rgba(255,200,61,0.14)]" /><span className="h-px min-w-7 flex-1 border-t border-dashed border-ink/20" /><span className="size-2 rounded-full bg-ink/25" /><span className="ml-1 whitespace-nowrap text-[10px] font-extrabold uppercase tracking-[0.15em] text-ink">Account protection</span></div></div>
    <div className="mt-6 space-y-4"><section className="overflow-hidden rounded-[26px] border border-ink/10 bg-white"><div className="flex items-start gap-3 border-b border-ink/8 p-5"><span className="grid size-10 place-items-center rounded-2xl bg-cargo-yellow text-ink"><Check className="size-4" /></span><div><p className="text-sm font-bold">Your account is protected</p><p className="mt-1 text-xs leading-5 text-ink/55">If you see a session you do not recognize, sign it out and change your password.</p></div></div>{sessions.map((item, index) => { const Icon = item.device.toLowerCase().includes("phone") || item.device.toLowerCase().includes("mobile") ? Smartphone : Laptop; return <div key={item.id} className={`flex gap-3 p-5 ${index ? "border-t border-ink/8" : ""}`}><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-cargo-yellow/15 text-ink"><Icon className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-bold">{item.device}</p>{item.current && <span className="rounded-full bg-cargo-yellow/30 px-2 py-0.5 text-[9px] font-bold text-ink">Current</span>}</div><p className="mt-1 flex items-center gap-1 text-xs text-ink/50"><MapPin className="size-3" />{item.location}</p><p className="mt-1 text-[11px] font-semibold text-ink/40">{item.displayLastActiveAt}</p></div>{!item.current && <Button variant="outline" disabled={sessionMutations.revoke.isPending} onClick={() => sessionMutations.revoke.mutate({ id: item.id, revision: item.revision })} className="h-9 shrink-0 rounded-xl px-3 text-xs font-bold"><LogOut className="mr-1 size-3.5" />Sign out</Button>}</div>; })}</section>
      {current && <section className="rounded-[26px] border border-ink/10 bg-white p-5"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-bold">Trust this device</p><p className="mt-1 text-xs leading-5 text-ink/55">Skip extra verification on this browser for 30 days.</p></div><button type="button" disabled={sessionMutations.setTrust.isPending} onClick={() => sessionMutations.setTrust.mutate({ id: current.id, revision: current.revision, trusted: !current.trusted })} className={`relative h-7 w-12 shrink-0 rounded-full transition ${current.trusted ? "bg-cargo-yellow" : "bg-ink/15"}`} aria-pressed={current.trusted}><span className={`absolute top-1 size-5 rounded-full bg-white shadow-sm transition ${current.trusted ? "left-6" : "left-1"}`} /></button></div></section>}
      {sessionMutations.revoke.isError || sessionMutations.setTrust.isError ? <p className="text-sm text-red-700">We could not update this device. Refresh and try again.</p> : null}
      <button type="button" onClick={() => navigate("/reset-password")} className="flex w-full items-center justify-between rounded-2xl border border-ink/10 bg-white px-5 py-4 text-left hover:bg-ink/[0.025]"><span><span className="block text-sm font-bold">Change password</span><span className="mt-1 block text-xs text-ink/50">Use a new password if you notice anything unusual.</span></span><ArrowLeft className="size-4 rotate-180 text-ink/35" /></button>
    </div>
  </div>;
}
